<b> Write a function so that the columns of the output matrix are powers of the input
vector. 
      
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1. </b>  
  
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde. 

In [1]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
N = 5

In [2]:
# creating matrix using built-in function np.vander
matrix01 = np.vander(x, N, increasing=False)
matrix01

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [3]:
# method-02
matrix02 = np.column_stack([x**(N-1-i) for i in range(N)])
matrix02

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
  
The moving average sequence has n-k+1 elements as shown below.
  
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
  
i 1 2 3 4 5 6 7 8 9 10  
===== == == == == == == == == == ==  
Input 10 20 30 40 50 60 70 80 90 100  
y1 25 = (10+20+30+40)/4  
y2 35 = (20+30+40+50)/4  
y3 45 = (30+40+50+60)/4  
y4 55 = (40+50+60+70)/4  
y5 65 = (50+60+70+80)/4  
y6 75 = (60+70+80+90)/4  
y7 85 = (70+80+90+100)/4  
Thus, the moving average sequence has n-k+1=10-4+1=7 values.  
  
<b>Question: Write a function to find moving average in an array over a window: 
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. </b>

In [4]:
import numpy as np

def moving_average(a, n=3) :
    
    #Create a vector of zeroes with the shape as n-k+1
    
    out_array = np.zeros(len(a) - n + 1)
    
    # Iterate over the input array. While doing so, for every element, get the next k elements through slicing, 
    # computer their mean and add to the output array.
    
    for i in range(n, len(a) + 1):
        out_array_moving_avg[i-n] = a[i-n:i].mean()
    
    return out_array_moving_avg 


a=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
#rounding off the results to two digts
moving_average_arr = np.array(moving_average(a,n=3)).round(2)
moving_average_arr

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])